apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: efk
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: harbor.mateusmuller.me/mateusmullerme/es-worker
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure